### ISSUE TITLE
error in line 308

### ISSUE THREAD

**Issue by nafergo** [davidswelt/zot_bib_web#13]
testing this great solution but returns...

<pre>  File &quot;./zot.py&quot;, line 308
    except AttributeError,ImportError:
                         ^
SyntaxError: invalid syntax
</pre>

any idea?

running Ubuntu 18.10

**Comment by davidswelt** [comment]
What's the Python version?

**Comment by davidswelt** [comment]
What solution?

**Comment by nafergo** [comment]
python --version is Python 2.7.16

But I also have installed Python 3.6.8

**Comment by davidswelt** [comment]
OK, thanks for reporting this.  I pushed a fix, please try it out and close
this bug if it works!

**Comment by nafergo** [comment]
hmm when I try to run ./zot.py --group 160464 DTDTV2EP
returns
Traceback (most recent call last):
  File "./zot.py", line 269, in <module>
    from pyzotero import zotero, zotero_errors
ModuleNotFoundError: No module named 'pyzotero'

**Comment by nafergo** [comment]
btw, the "great solution" is zot_bib_web :) I meant it looks great,  what I was looking for :)

**Comment by davidswelt** [comment]
Is there no read me file?  It needs that module.

**Comment by nafergo** [comment]
pip install pyzotero returns 
Successfully installed bibtexparser-1.1.0 certifi-2019.9.11 chardet-3.0.4 feedparser-5.2.1 future-0.18.2 idna-2.8 pathlib-1.0.1 pyparsing-2.4.5 pytz-2019.3 pyzotero-1.4.10 requests-2.22.0 urllib3-1.25.7

I assumed  pyzotero-1.4.10 is pyzotero... 
What readme file?

**Comment by davidswelt** [comment]
Try pip3

I recently switched zotbibweb to python3.

**Comment by nafergo** [comment]
Moving forward :)
1º sudo apt install python3-pip
2º pip3 install pyzotero
3º ./zot.py --group 160464 DTDTV2EP

returns 

ERROR:  settings.py file could not be read or processed.
Traceback (most recent call last):
  File "./zot.py", line 2452, in <module>
    Settings.read_args_and_init()
  File "./zot.py", line 401, in read_args_and_init
    Settings.load_settings()
  File "./zot.py", line 335, in load_settings
    raise e
  File "./zot.py", line 307, in load_settings
    settings = importlib.machinery.SourceFileLoader("settings", loadfile).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'settings.py'

**Comment by davidswelt** [comment]
Thanks, I committed a few more changes that revert back to the default python installed on the system (usually Python 2.7) and that revise the error handling for missing settings files.

You will still have to write a settings.py file or use command line arguments.  See README.rst.

**Comment by nafergo** [comment]
ok it seems to work, now. will close this and open a new one if a new issue comes up. next yeat, I will use this for an archaeology group lib :). I'll send you the link and credit you ;)
